spring:
  application:
    name: sp-orchestrator-api-poc

  # Database Configuration (H2 for demo)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /sp-orchestrator

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    com.uenobank.sporchestratorapi: INFO
    io.github.resilience4j: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      default:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
      currency-service:
        failure-rate-threshold: 30
        wait-duration-in-open-state: 10s
        sliding-window-size: 20
        minimum-number-of-calls: 3
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
      loan-simulation-service:
        failure-rate-threshold: 60
        wait-duration-in-open-state: 60s
        sliding-window-size: 15
        minimum-number-of-calls: 10
        slow-call-duration-threshold: 5s
        slow-call-rate-threshold: 40

  ratelimiter:
    instances:
      default:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 500ms
      currency-service:
        limit-for-period: 50
        limit-refresh-period: 1s
        timeout-duration: 200ms
      loan-simulation-service:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 1s

  bulkhead:
    instances:
      default:
        max-concurrent-calls: 5
        max-wait-duration: 100ms
      currency-service:
        max-concurrent-calls: 10
        max-wait-duration: 50ms
      loan-simulation-service:
        max-concurrent-calls: 3
        max-wait-duration: 200ms

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Cache Configuration
cache-config:
  default:
    ttl-seconds: 15
    max-size: 1000
  caches:
    - name: currency
      ttl-seconds: 5
      max-size: 50
    - name: loanSimulation
      ttl-seconds: 10
      max-size: 5000
